### ISSUE TITLE
Can't use mpi to run "mpriun -np 10 python SHC_generate.py"

### ISSUE THREAD

**Issue by visionshao** [Tingliangstu/New-Version-Spectral-decomposition-python-tools#1]
Thanks for your code. I try to reproduce the case you posted recently. But when I try to use mpi to run the final step. Something goes wrong like this figure.
![8fa8a8de1cdded661e6c5dec603e64e](https://user-images.githubusercontent.com/26805617/193622648-71adf32a-667d-41ab-8291-c90766a7fc94.jpg)

**Comment by Tingliangstu** [comment]
Thanks for your report. This issue seems not caused by running mpi. So, you can simply comment this line "os.remove('dump.left')" and try again. Or you can provide more detail then I can help you.

**Comment by Tingliangstu** [comment]
seem no response, I will close it

**Comment by Tingliangstu** [comment]
seem no response, I will close it
