### ISSUE TITLE
Dismatch between temp_jump in SHC_genereate.py and lammps file

### ISSUE THREAD

**Issue by visionshao** [Tingliangstu/New-Version-Spectral-decomposition-python-tools#2]
Hi, I find the delta temperature is 60K in your lammps files. However, the temp_jump in your SHC_generete.py is 19.3. Is there a unit transformation or other processings?

**Comment by Tingliangstu** [comment]
In my example, the temp_jump is given by the real jump in the my simulation between two interface. It is not between the heat source and heat sink. 
This definition is quite casual. So u can define it according to the simulation.

**Comment by Tingliangstu** [comment]
Achieved.
