### ISSUE TITLE
How to get the restart file which is needed in the force _calculate.py

### ISSUE THREAD

**Issue by yhf135** [Tingliangstu/New-Version-Spectral-decomposition-python-tools#3]
Thanks for your code. I try to reproduce the case you posted recently．But I am new in lammps .so  when I try the script force_calculate.py ,it says:"Exception: ERROR on proc 0: Cannot open restart file optimize.restart: No such file or directory (../read_rest"
I also noticed that file was not an attribute in your script in the comments(:param restartfile: LAMMPS restart file (The restart file is also required, but here not as an attribute),I would appreciate it if you can give me some advise,thank you very much.

**Comment by Tingliangstu** [comment]
hi, there is a restart file in your running directory? u have generated a restart file from lammps?



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/27/2024 19:08 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [Tingliangstu/New-Version-Spectral-decomposition-python-tools] How to get the restart file which is needed in the force _calculate.py (Issue #3) |

Thanks for your code. I try to reproduce the case you posted recently．But I am new in lammps .so when I try the script force_calculate.py ,it says:"Exception: ERROR on proc 0: Cannot open restart file optimize.restart: No such file or directory (../read_rest"
I also noticed that file was not an attribute in your script in the comments(:param restartfile: LAMMPS restart file (The restart file is also required, but here not as an attribute),I would appreciate it if you can give me some advise,thank you very much.

**Comment by yhf135** [comment]
hi，thank you for your reply！I just want to try your example first，so there is no restart file in my lammps generation，by the way，I have no idea about the restart file，could you please give me some details &nbsp;about it，or how to get it from lammps！that will help me&nbsp;
alot，thank you！

发自我的iPhone


------------------ Original ------------------
From: Liangting ***@***.***&gt;
Date: Sun,Jan 28,2024 9:33 PM
To: Tingliangstu/New-Version-Spectral-decomposition-python-tools ***@***.***&gt;
Cc: 杨海飞 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Tingliangstu/New-Version-Spectral-decomposition-python-tools]How to get the restart file which is needed in the force _calculate.py (Issue#3)





 hi, there is a restart file in your running directory? u have generated a restart file from lammps?
 
 
 
 ---- Replied Message ----
 | From | ***@***.***&gt; |
 | Date | 01/27/2024 19:08 |
 | To | ***@***.***&gt; |
 | Cc | ***@***.***&gt; |
 | Subject | [Tingliangstu/New-Version-Spectral-decomposition-python-tools] How to get the restart file which is needed in the force _calculate.py (Issue #3) |
 
 Thanks for your code. I try to reproduce the case you posted recently．But I am new in lammps .so when I try the script force_calculate.py ,it says:"Exception: ERROR on proc 0: Cannot open restart file optimize.restart: No such file or directory (../read_rest"
 I also noticed that file was not an attribute in your script in the comments(:param restartfile: LAMMPS restart file (The restart file is also required, but here not as an attribute),I would appreciate it if you can give me some advise,thank you very much.

**Comment by Tingliangstu** [comment]
hi, u have to generate a restart file by running lammps again even if u want to reproduce the example. Then the restart file would be suitable for your machine. Btw, u can simply rerun the thermal.in in the example directory, then the restart file would be generated. For more details, see Readme.

**Comment by yhf135** [comment]
Thank you very much! I got it!



发自我的iPhone


------------------ Original ------------------
From: Liangting ***@***.***&gt;
Date: Mon,Jan 29,2024 11:34 AM
To: Tingliangstu/New-Version-Spectral-decomposition-python-tools ***@***.***&gt;
Cc: 杨海飞 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Tingliangstu/New-Version-Spectral-decomposition-python-tools]How to get the restart file which is needed in the force _calculate.py (Issue#3)





 
hi, u have to generate a restart file by running lammps again even if u want to reproduce the example. Then the restart file would be suitable for your machine. Btw, u can simply rerun the thermal.in in the example directory, then the restart file would be generated. For more details, see Readme.

**Comment by yhf135** [comment]
Hi, with your help, I have run the thermal.in and  force_calculate.py successfully,and I also follow the readme file to generate the compactify_vels from compactify_vels.cpp script and I add it to the SHC_calculate file, but when I run the SHC_generate.py script, the command line have the error: FileNotFoundError: [Errno 2] No such file or directory: 'compactify_vels', can you help me to solve it. By the way, the generate_force.log is:

LAMMPS (2 Aug 2023 - Update 2)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Loaded 1 plugins from C:\Users\18066\AppData\Local\LAMMPS 64-bit 2Aug2023-MSMPI with Python\plugins
Total wall time: 0:00:00

I'm sorry for spending a lot of your time answering my question today！
thanks!

**Comment by Tingliangstu** [comment]
Already sovled
